frontend/package.json, frontend/src/component/MainPage.js, frontend/src/index.js, frontend/webpack.config.js
Added file-loader in webpack
added import css in index.css
added PF4 Button in MainPage.js
=> fixed import PF4 CSS issue using file-loader

frontend/src/component/PageBase.js, frontend/src/component/common/MockupData.js, frontend/src/component/page1/Page1.js, frontend/src/component/page2/Page2.js
pls ignore the changes in page1, what I did is just revert it back to old state since we have the dynamic form example, no need to leave static ones there.
=> validation example for dynamice form

.travis.yml, Makefile, README.md, cmd/testwebapp.go
Signed-off-by: tchughesiv <tchughesiv@gmail.com>
=> add travis-ci & Makefile

README.md
Signed-off-by: tchughesiv <tchughesiv@gmail.com>
=> add travis-ci badge

frontend/src/component/Main.js, frontend/src/component/operator-wizard/FormJsonLoader.js, frontend/src/component/operator-wizard/OperatorWizard.js, frontend/src/component/operator-wizard/StepBuilder.js, frontend/src/component/operator-wizard/element-component/ElementFactory.js, frontend/src/component/operator-wizard/element-component/button-element/ButtonElement.js, frontend/src/component/operator-wizard/element-component/button-element/ButtonGroup.js, frontend/src/component/operator-wizard/element-component/field-factory/CheckboxField.js, frontend/src/component/operator-wizard/element-component/field-factory/DefaultTextField.js, frontend/src/component/operator-wizard/element-component/field-factory/DropdownField.js, frontend/src/component/operator-wizard/element-component/field-factory/EmailField.js, frontend/src/component/operator-wizard/element-component/field-factory/FieldFactory.js, frontend/src/component/operator-wizard/element-component/field-factory/FieldUtils.js, frontend/src/component/operator-wizard/element-component/field-factory/ObjectField.js, frontend/src/component/operator-wizard/element-component/field-factory/PasswordField.js, frontend/src/component/operator-wizard/element-component/field-factory/RadioButtonField.js, frontend/src/component/operator-wizard/element-component/field-factory/SectionField.js, frontend/src/component/operator-wizard/element-component/field-factory/SectionRadioField.js, frontend/src/component/operator-wizard/element-component/field-factory/SeparateDivField.js, frontend/src/component/operator-wizard/element-component/field-factory/TextAreaField.js, frontend/src/component/operator-wizard/element-component/field-factory/UrlField.js, frontend/src/component/operator-wizard/page-component/Page.js
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
This is the refactoring of the Operator UI to make it easier to add and manipulate the elements during the wizard flow. 
To use it, simply change the `MainPage` import to `Main` in the `index.js` file.
=> Operator UI Wizard Refactoring

frontend/package-lock.json, frontend/package.json, frontend/src/component/common/MockupData.js, frontend/src/component/operator-wizard/element-component/field-factory/ObjectField.js, frontend/src/component/operator-wizard/page-component/Page.js, package-lock.json
After messed up with the last PR, this is a brand new one with the feature requested
Signed-off-by: Ricardo Zanini <zanini@redhat.com>
=> [KIECLOUD-177] Add min/max element rule to dynamic field defs

frontend/package-lock.json, frontend/src/component/operator-wizard/page-component/Page.js, pkg/web/configuration.go, pkg/web/http.go
On deploy, post the yaml to own URL and pass it on to operator through callback
=> Further integration with operator for deployment

frontend/src/component/common/MockupData.js, frontend/src/component/operator-wizard/StepBuilder.js, frontend/src/component/operator-wizard/element-component/field-factory/CheckboxField.js, frontend/src/component/operator-wizard/element-component/field-factory/DefaultTextField.js, frontend/src/component/operator-wizard/element-component/field-factory/DropdownField.js, frontend/src/component/operator-wizard/element-component/field-factory/EmailField.js, frontend/src/component/operator-wizard/element-component/field-factory/PasswordField.js, frontend/src/component/operator-wizard/element-component/field-factory/TextAreaField.js, frontend/src/component/operator-wizard/element-component/field-factory/UrlField.js, frontend/src/component/operator-wizard/page-component/Page.js
=> Form Data persistence

cmd/testwebapp.go, frontend/dist/index.html, frontend/package-lock.json, frontend/src/component/operator-wizard/page-component/Page.js, pkg/web/configuration.go, pkg/web/http.go
Added ApiVersion and Kind so proper and full CR yaml can be generated from user input
Refactored interface to enforce callback
=> Further integration with back-end / operator

frontend/package-lock.json, frontend/src/component/common/MockupData.js, frontend/src/component/operator-wizard/page-component/Page.js
=> Rectified deploy yaml

Gopkg.lock, frontend/package-lock.json
Go build was failing due to a lack of sync of the Gopkg.lock file
=> Fix go build

frontend/src/component/common/MockupData.js
Marking required fields in SSO and ldap
=> Marking required fields in SSO and ldap

frontend/src/component/Main.js, frontend/src/component/operator-wizard/OperatorWizard.js, frontend/src/component/operator-wizard/OperatorWizardFooter.js, frontend/src/component/operator-wizard/StepBuilder.js
A custom footer allows us to have more control over what buttons are displayed.
I will include the Deploy button in the next PR but it requires some refactoring due to the dependency with the `Edit YAML` button
=> Add custom footer

frontend/package-lock.json
=> Add missing packr file

pkg/web/form.go
=> align go model

test/examples/full-form.json
Updated labels and added descriptions, while also tweaking and correcting the form definition in certain spots
=> Updated labels, added descriptions, made some corrections

frontend/package-lock.json, frontend/src/component/operator-wizard/element-component/field-factory/ObjectField.js, test/examples/full-form.json
Added separation between repeating block
=> Added separation between repeating block

frontend/src/component/operator-wizard/OperatorWizardFooter.js, test/examples/full-form.json, test/examples/full-schema.json
Multiple changes to the form, as well as a rename of Edit Yaml to View Yaml
=> Form changes

frontend/package-lock.json, frontend/server.js, frontend/src/component/operator-wizard/OperatorWizard.js, frontend/src/component/operator-wizard/element-component/field-factory/DefaultTextField.js, frontend/src/component/operator-wizard/element-component/field-factory/DropdownField.js, frontend/src/component/operator-wizard/element-component/field-factory/EmailField.js, frontend/src/component/operator-wizard/element-component/field-factory/PasswordField.js, frontend/src/component/operator-wizard/element-component/field-factory/TextAreaField.js, frontend/src/component/operator-wizard/element-component/field-factory/UrlField.js, frontend/webpack.config.js, test/examples/full-form.json
Show default values when provided in InputText and Dropdown fields
Fix regression for fieldGroups
=> Default values as placeholders

frontend/src/component/operator-wizard/element-component/field-factory/FieldFactory.js, frontend/src/component/operator-wizard/element-component/field-factory/FieldGroupField.js, frontend/src/component/operator-wizard/element-component/field-factory/FieldUtils.js, frontend/src/component/operator-wizard/element-component/field-factory/ObjectField.js, pkg/web/form.go, test/examples/full-form.json
I added an ugly hack to allow us to have a 3rd level of objects to cover this use case:
Servers[*].Webhooks[*].*
Added the following groups:
* RoleMapping
* Resource Quotas
* Build
* SSO Client
* Database
=> Added more groups and allow 3rd level

frontend/src/component/operator-wizard/OperatorWizard.js, frontend/src/component/operator-wizard/OperatorWizardFooter.js, frontend/src/component/operator-wizard/page-component/Page.js
* Add html page title
* Change "View YAML" button to type "link"
* Revert back to vertical form
=> UXD review part2

test/examples/full-form.json
Refactored security form to extract common section and change some descriptions
Fixed Packr file after having to rebase PR
=> Refactored security form & fixed Packr file

frontend/src/component/operator-wizard/element-component/field-factory/DropdownField.js
Bug fix for DropDown default value to take effect
=> Bug fix for DropDown default value to take effect

.gitignore, frontend/src/component/operator-wizard/element-component/field-factory/DropdownField.js, package-lock.json, test/examples/full-form.json
=> Bug fix for dropdown value change with default

frontend/src/component/operator-wizard/OperatorWizard.js, frontend/src/component/operator-wizard/element-component/field-factory/FieldFactory.js, frontend/src/component/operator-wizard/element-component/field-factory/IntegerField.js, test/examples/full-form.json
=> Integer Fields handling

test/examples/full-form.json
=> Smart Router as an optional in yaml

frontend/src/component/operator-wizard/OperatorWizard.js, frontend/src/component/operator-wizard/element-component/field-factory/DropdownField.js, frontend/src/component/operator-wizard/element-component/field-factory/PasswordField.js
=> Messages on view  and deploy yaml

test/examples/full-form.json
Renamed process server to KIE server
=> Renamed process server to KIE server

test/examples/full-form.json
=> Changed Process server to KIE server in Id description

frontend/package-lock.json, frontend/package.json
Fix https://issues.jboss.org/browse/KIECLOUD-235
=> [KIECLOUD-235] Removed unused dependency - axios

frontend/package-lock.json, frontend/src/component/operator-wizard/element-component/ElementFactory.js, frontend/src/component/operator-wizard/element-component/field-factory/CheckboxField.js, frontend/src/component/operator-wizard/element-component/field-factory/DefaultTextField.js, frontend/src/component/operator-wizard/element-component/field-factory/DropdownField.js, frontend/src/component/operator-wizard/element-component/field-factory/EmailField.js, frontend/src/component/operator-wizard/element-component/field-factory/FieldFactory.js, frontend/src/component/operator-wizard/element-component/field-factory/FieldGroupField.js, frontend/src/component/operator-wizard/element-component/field-factory/IntegerField.js, frontend/src/component/operator-wizard/element-component/field-factory/ObjectField.js, frontend/src/component/operator-wizard/element-component/field-factory/PasswordField.js, frontend/src/component/operator-wizard/element-component/field-factory/TextAreaField.js, frontend/src/component/operator-wizard/element-component/field-factory/UrlField.js, frontend/src/component/operator-wizard/page-component/Page.js
Fix https://issues.jboss.org/browse/KIECLOUD-234
=> [KIECLOUD-234] Field validations on change of their values

frontend/src/component/operator-wizard/OperatorWizard.js, frontend/src/component/operator-wizard/OperatorWizardFooter.js, frontend/src/component/operator-wizard/StepBuilder.js, frontend/src/component/operator-wizard/page-component/Page.js, frontend/src/component/operator-wizard/page-component/ReviewPage.js
Fix https://issues.jboss.org/browse/KIECLOUD-233
* Removed deployed modal
* Renamed editYaml modal
* Validation modal shows first validation error
* Fixed error handling upon deployment
* Hide Next/Deploy/Back buttons after deployment
=> [KIECLOUD-233] Add confirmation page

frontend/src/component/operator-wizard/OperatorWizard.js, frontend/src/component/operator-wizard/element-component/field-factory/DropdownField.js
=> [KIECLOUD-234] Validations on edit and deploy Yaml

cmd/testwebapp.go, frontend/server.js, frontend/src/component/operator-wizard/OperatorWizard.js, frontend/src/component/operator-wizard/page-component/ReviewPage.js, pkg/web/configuration.go, pkg/web/http.go
Fix https://issues.jboss.org/browse/KIECLOUD-233
When the deployment fails, the error should be propagated to the UI
=> [KIECLOUD-233] Propagate deployment errors to UI

pkg/web/http.go
Fix https://issues.jboss.org/browse/KIECLOUD-233
=> [KIECLOUD-233] Replace go1.12 ReplaceAll

cmd/testwebapp.go, pkg/web/http.go
Fix https://issues.jboss.org/browse/KIECLOUD-239
=> [KIECLOUD-239] Log CR errors in debug level

frontend/src/component/operator-wizard/FormJsonLoader.js, frontend/src/component/operator-wizard/OperatorWizard.js
Fix https://issues.jboss.org/browse/KIECLOUD-241
=> [KIECLOUD-241] Forward oauth credentials in XHR requests

frontend/src/component/operator-wizard/OperatorWizard.js, frontend/src/component/operator-wizard/element-component/field-factory/ObjectField.js, test/examples/full-form.json
Fix https://issues.jboss.org/browse/KIECLOUD-240
Default max is -1 meaning it's unbounded.
Default min is 0
=> [KIECLOUD-240] Fix validation issue and remove min/max from form

frontend/src/component/operator-wizard/OperatorWizard.js, test/examples/full-form.json
Partial fix for https://issues.jboss.org/projects/KIECLOUD/issues/KIECLOUD-253
Requires same change in kie-cloud-operator
=> [KIECLOUD-253] Replace sso client literals

test/examples/full-form.json
Fix https://issues.jboss.org/projects/KIECLOUD/issues/KIECLOUD-255
=> [KIECLOUD-255] Rename immutable group

test/examples/full-form.json
Fix https://issues.jboss.org/projects/KIECLOUD/issues/KIECLOUD-254
=> [KIECLOUD-254] Remove JNDI field

frontend/package-lock.json
Performed `npm audit fix` to fix Javascript vulnerabilities by upgrading npm dependencies.
=> fixed js deps vulnerabilities

frontend/package-lock.json, frontend/src/component/operator-wizard/OperatorWizard.js, frontend/src/component/operator-wizard/OperatorWizardFooter.js, frontend/src/component/operator-wizard/element-component/field-factory/ObjectField.js, test/examples/full-form.json
Fix https://issues.jboss.org/browse/RHPAM-2245
Fix https://issues.jboss.org/browse/RHPAM-2246
Fix https://issues.jboss.org/browse/RHPAM-2247
Fix https://issues.jboss.org/browse/RHPAM-2248
=> UI Defects for 7.5

frontend/src/component/common/GuiConstants.js, frontend/src/component/operator-wizard/OperatorWizard.js, frontend/src/component/operator-wizard/element-component/field-factory/DropdownField.js, frontend/src/component/operator-wizard/page-component/Page.js
=> [RHPAM-2249] Skip Smart router configuration for RHDM environments

frontend/src/component/operator-wizard/element-component/field-factory/CheckboxField.js, test/examples/full-form.json
=> [RHPAM-2205] - Add AMQ support to Operator installer UI

test/examples/full-form.json, test/examples/full-schema.json
Fix https://issues.jboss.org/browse/RHPAM-2175
=> [RHPAM-2175] Remove controllerUser and executionUser

frontend/src/component/common/GuiConstants.js, frontend/src/component/operator-wizard/OperatorWizard.js
…d namespace for external DB driver in Operator UI
=> [RHPAM-2522] - Provide usable way of setting extensions image name and namespace for external DB driver in Operator UI

frontend/package-lock.json
Signed-off-by: tchughesiv <tchughesiv@gmail.com>
=> [RHPAM-2249] packr file fixes

test/examples/full-form.json, test/examples/full-schema.json
=> [RHPAM-2497] - PIM - Operator console integration

frontend/src/component/common/GuiConstants.js, frontend/src/component/operator-wizard/OperatorWizard.js, frontend/src/component/operator-wizard/page-component/Page.js
=> PIM - Available for RHPAM and not for RHDM env

test/examples/full-form.json
=> Removed "default" for extension images - Minor fix

test/examples/full-form.json, test/examples/full-schema.json
=> Removed Bug due to extension Img checkbox 

test/examples/full-form.json, test/examples/full-schema.json
=> [BAPL-1507] Add to OpenShift images property for JVM max memory ratio conf

frontend/dist/build-hash.json, frontend/package-lock.json
Signed-off-by: tchughesiv <tchughesiv@gmail.com>
=> resolve npm dep vulnerabilities
